package com.example.neofin.utils

object Constants {
    const val BASE_URL = "https://neo-fms.herokuapp.com"
    const val LOGIN_URL = "/login"
    const val HOME_URL = "/home"
    const val HOME_URL_BY_PERIOD = "/home/{period}"
    const val JOURNAL_URL = "/journal/getAll"
    const val JOURNAL_SINGLE_URL = "/journal/getById/{id}"
    const val ADD_INCOME_EXPENSE = "/transaction/addIncomeOrExpense"
    const val ADD_TRANSFER = "/transaction/addTransfer"
    const val CATEGORY_ALL = "/category/getAllActiveCategoriesBySectionAndType"
    const val GET_WALLETS = "/wallet/getAllActiveWallets"
    const val GET_CURRENT_USER = "/user/getCurrentUser"
    const val GET_JOURNAL_BY_SECTION = "/journal/getByNeoSection"
    const val GET_FILTERED = "/transaction/getByGlobalFiltration"
    const val GET_ALL_USERS = "/user/getAllUsers"
    const val GET_ALL_AGENTS = "/people/getAllCounterparties"
    const val GET_ANALYTICS = "/transaction/getAnalytics"
    const val GET_ALL_CATEGORY = "/category/getAll"
    const val GET_ALL_GROUPS_ARCHIVE = "/group/getAll"
    const val GET_ALL_GROUPS = "/group/getAllActiveGroups"
    const val GET_ALL_WALLETS = "/wallet/getAll"
    const val CHANGE_PASSWORD ="/user/changePassword"
    const val ADD_USER = "/registration/newAccountant"
    const val ADD_WALLET = "/wallet/add"
    const val ADD_CATEGORY = "/category/add"
    const val ADD_GROUP = "/group/add"
    const val ARCHIVE_WALLET = "/wallet/update"
    const val ARCHIVE_CATEGORY = "/category/update"
    const val ARCHIVE_GROUPS = "/group/update"
    const val UPDATE_JOURNAL_ITEM = "/transaction/updateTransaction"
    const val UPDATE_USER = "/user/updateUser"
}